/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sxi.Sai (https://sketchfab.com/Sxi.Sai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/f1-ayrton-senna-1991-car-644d9113ab004e118d955b199a7f485b
Title: F1 Ayrton Senna 1991 car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import f1car from "../assets/f1car.glb"

export function F1Car(props) {
    const { nodes, materials } = useGLTF(f1car);
    return (
        <group {...props} dispose={null}>
            <group scale={0.01}>
                <group
                    position={[25.625, 58.461, -145.653]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[1578.728, 1613.448, 1862.855]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface2_ChassisBlack_0.geometry}
                        material={materials.ChassisBlack}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    />
                    <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface24_primitive0_BodyTexture_0.geometry}
                            material={materials.BodyTexture}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface24_primitive1_lambert1_0.geometry}
                            material={materials.lambert1}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface24_primitive2_BodyworkRed_0.geometry}
                            material={materials.BodyworkRed}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface24_primitive3_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface24_primitive4_BodyworkWhite_0.geometry}
                            material={materials.BodyworkWhite}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface24_primitive5_BodyworkBlackGloss_0.geometry}
                            material={materials.BodyworkBlackGloss}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface24_primitive6_window_0.geometry}
                            material={materials.material_0}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface25_window_0.geometry}
                            material={materials.material_0}
                            position={[0, -2.12, 0]}
                        />
                    </group>
                    <group position={[-0.088, 0, -0.081]} rotation={[1.57, -0.017, -0.035]} scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface40_Rim_0.geometry}
                            material={materials.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface41_Tyre_0.geometry}
                            material={materials.Tyre}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface42_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface43_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface44_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface45_BodyworkBlackGloss_0.geometry}
                            material={materials.BodyworkBlackGloss}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface46_driveShaft_0.geometry}
                            material={materials.driveShaft}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface47_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface48_driveShaft_0.geometry}
                            material={materials.driveShaft}
                        />
                    </group>
                    <group
                        position={[0.088, 0, -0.081]}
                        rotation={[1.57, 0.017, 0.035]}
                        scale={[-0.01, 0.01, 0.01]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface58_Rim_0.geometry}
                            material={materials.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface59_Tyre_0.geometry}
                            material={materials.Tyre}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface60_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface61_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface62_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface63_BodyworkBlackGloss_0.geometry}
                            material={materials.BodyworkBlackGloss}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface64_driveShaft_0.geometry}
                            material={materials.driveShaft}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface65_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface66_driveShaft_0.geometry}
                            material={materials.driveShaft}
                        />
                    </group>
                    <group
                        position={[0.085, -0.001, -0.182]}
                        rotation={[1.571, -0.017, 0.017]}
                        scale={[-0.014, 0.01, 0.01]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface67_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface68_BodyworkBlackGloss_0.geometry}
                            material={materials.BodyworkBlackGloss}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface69_driveShaft_0.geometry}
                            material={materials.driveShaft}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface70_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface71_driveShaft_0.geometry}
                            material={materials.driveShaft}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface72_Tyre_0.geometry}
                            material={materials.Tyre}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface73_Rim_0.geometry}
                            material={materials.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface74_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface75_pedal_0.geometry}
                            material={materials.pedal}
                        />
                    </group>
                    <group
                        position={[-0.018, -0.007, -0.061]}
                        rotation={[Math.PI / 2, -0.105, 0]}
                        scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder39_primitive0_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder39_primitive1_BodyworkWhite_0.geometry}
                            material={materials.BodyworkWhite}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder39_primitive2_mirror_0.geometry}
                            material={materials.mirror}
                        />
                    </group>
                    <group
                        position={[0.018, -0.007, -0.061]}
                        rotation={[Math.PI / 2, 0.105, 0]}
                        scale={[-0.01, 0.01, 0.01]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder40_primitive0_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder40_primitive1_BodyworkWhite_0.geometry}
                            material={materials.BodyworkWhite}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder40_primitive2_mirror_0.geometry}
                            material={materials.mirror}
                        />
                    </group>
                    <group
                        position={[0, 0.025, -0.009]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.01, 0.012, 0.014]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder44_primitive0_BodyworkWhite_0.geometry}
                            material={materials.BodyworkWhite}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder44_primitive1_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                    </group>
                    <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCube154_primitive0_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCube154_primitive1_FrontWing_0.geometry}
                            material={materials.FrontWing}
                        />
                    </group>
                    <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCube156_primitive0_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCube156_primitive1_driveShaft_0.geometry}
                            material={materials.driveShaft}
                        />
                    </group>
                    <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface19001_primitive0_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface19001_primitive1_Rearwing_0.geometry}
                            material={materials.Rearwing}
                        />
                    </group>
                    <group position={[0, 0, -0.061]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder51_primitive0_green_button_0.geometry}
                            material={materials.green_button}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder51_primitive1_BodyworkRed_0.geometry}
                            material={materials.BodyworkRed}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder51_primitive2_steeringWheel_0.geometry}
                            material={materials.steeringWheel}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder51_primitive3_leather_0.geometry}
                            material={materials.leather}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder51_primitive4_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                    </group>
                    <group
                        position={[-0.084, -0.001, -0.113]}
                        rotation={[1.571, 0.017, -0.017]}
                        scale={[0.014, 0.01, 0.01]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder93_primitive0_Rim_0.geometry}
                            material={materials.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder93_primitive1_Tyre_0.geometry}
                            material={materials.Tyre}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder93_primitive2_pedal_0.geometry}
                            material={materials.pedal}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder93_primitive3_ChassisBlack_0.geometry}
                            material={materials.ChassisBlack}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder93_primitive4_BodyworkBlackGloss_0.geometry}
                            material={materials.BodyworkBlackGloss}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder93_primitive5_driveShaft_0.geometry}
                            material={materials.driveShaft}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCylinder21_lambert1_0.geometry}
                        material={materials.lambert1}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCylinder22_lambert1_0.geometry}
                        material={materials.lambert1}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCube130_Tach_0.geometry}
                        material={materials.Tach}
                        position={[0, -0.149, 0.026]}
                        rotation={[1.695, 0, 0]}
                        scale={[0.01, 0.01, 0.021]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCube133_seat_0.geometry}
                        material={materials.seat}
                        position={[0, 0.021, -0.102]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.01, 0.01, 0.012]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCone1_shiftknob_0.geometry}
                        material={materials.shiftknob}
                        position={[-0.017, -0.114, 0.014]}
                        rotation={[Math.PI / 2, 0, Math.PI]}
                        scale={0.002}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCube145_pedal_0.geometry}
                        material={materials.pedal}
                        position={[0, -0.031, -0.09]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCube158_Tachometer_0.geometry}
                        material={materials.Tachometer}
                        position={[0, -0.142, 0.027]}
                        rotation={[1.693, 0, 0]}
                        scale={0.01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCube48_BodyworkRed_0.geometry}
                        material={materials.BodyworkRed}
                        position={[-0.023, 0.006, -0.032]}
                        rotation={[1.536, 0, 0]}
                        scale={0.01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pCube49_BodyworkRed_0.geometry}
                        material={materials.BodyworkRed}
                        position={[0.023, 0.006, -0.032]}
                        rotation={[1.536, 0, 0]}
                        scale={0.01}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(f1car)
